/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DoctorId = IDL.Nat;
export const SlotInput = IDL.Record({
  'startTime' : IDL.Text,
  'doctorId' : DoctorId,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
});
export const SlotId = IDL.Nat;
export const AvailabilitySlot = IDL.Record({
  'id' : SlotId,
  'startTime' : IDL.Text,
  'doctorId' : DoctorId,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const AppointmentId = IDL.Nat;
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'bookedAt' : Timestamp,
  'patientId' : UserId,
  'slotId' : SlotId,
  'notes' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentInput = IDL.Record({
  'doctorId' : DoctorId,
  'slotId' : SlotId,
  'notes' : IDL.Opt(IDL.Text),
});
export const DoctorInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'clinicAddress' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'clinicName' : IDL.Text,
});
export const Doctor = IDL.Record({
  'id' : DoctorId,
  'bio' : IDL.Opt(IDL.Text),
  'clinicAddress' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'clinicName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ReportType = IDL.Variant({
  'mri' : IDL.Null,
  'bloodTest' : IDL.Null,
  'other' : IDL.Text,
  'xRay' : IDL.Null,
  'ctScan' : IDL.Null,
  'ultrasound' : IDL.Null,
});
export const ReportInput = IDL.Record({
  'title' : IDL.Text,
  'patientId' : UserId,
  'labNotes' : IDL.Opt(IDL.Text),
  'fileBlob' : IDL.Opt(ExternalBlob),
  'reportType' : ReportType,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'adminNotes' : IDL.Opt(IDL.Text),
});
export const ReportId = IDL.Nat;
export const ReportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'uploaded' : IDL.Null,
  'viewed' : IDL.Null,
});
export const DiagnosticReport = IDL.Record({
  'id' : ReportId,
  'status' : ReportStatus,
  'title' : IDL.Text,
  'patientId' : UserId,
  'labNotes' : IDL.Opt(IDL.Text),
  'fileBlob' : IDL.Opt(ExternalBlob),
  'reportType' : ReportType,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'adminNotes' : IDL.Opt(IDL.Text),
  'uploadedAt' : Timestamp,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PatientProfile = IDL.Record({
  'id' : UserId,
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
  'phone' : IDL.Text,
});
export const PatientProfileInput = IDL.Record({
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
  'phone' : IDL.Text,
});
export const ReportUpdate = IDL.Record({
  'status' : IDL.Opt(ReportStatus),
  'title' : IDL.Opt(IDL.Text),
  'labNotes' : IDL.Opt(IDL.Text),
  'fileBlob' : IDL.Opt(ExternalBlob),
  'reportType' : IDL.Opt(ReportType),
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'adminNotes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addDoctorSlot' : IDL.Func([SlotInput], [AvailabilitySlot], []),
  'adminCancelAppointment' : IDL.Func(
      [AppointmentId],
      [IDL.Opt(Appointment)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([AppointmentInput], [Appointment], []),
  'cancelMyAppointment' : IDL.Func([AppointmentId], [IDL.Opt(Appointment)], []),
  'confirmAppointment' : IDL.Func([AppointmentId], [IDL.Opt(Appointment)], []),
  'createDoctor' : IDL.Func([DoctorInput], [Doctor], []),
  'createReport' : IDL.Func([ReportInput], [DiagnosticReport], []),
  'deleteDoctor' : IDL.Func([DoctorId], [], []),
  'deletePatient' : IDL.Func([UserId], [], []),
  'deleteReport' : IDL.Func([ReportId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(Doctor)], ['query']),
  'getDoctorSlots' : IDL.Func(
      [DoctorId],
      [IDL.Vec(AvailabilitySlot)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
  'getPatientProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getReport' : IDL.Func([ReportId], [IDL.Opt(DiagnosticReport)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listAllPatients' : IDL.Func([], [IDL.Vec(PatientProfile)], ['query']),
  'listAllReports' : IDL.Func([], [IDL.Vec(DiagnosticReport)], ['query']),
  'listDoctors' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Doctor)], ['query']),
  'listMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listMyReports' : IDL.Func([], [IDL.Vec(DiagnosticReport)], ['query']),
  'markReportViewed' : IDL.Func([ReportId], [IDL.Opt(DiagnosticReport)], []),
  'removeDoctorSlot' : IDL.Func([SlotId], [], []),
  'saveMyProfile' : IDL.Func([PatientProfileInput], [PatientProfile], []),
  'setReportStatus' : IDL.Func(
      [ReportId, ReportStatus],
      [IDL.Opt(DiagnosticReport)],
      [],
    ),
  'updateDoctor' : IDL.Func([DoctorId, DoctorInput], [IDL.Opt(Doctor)], []),
  'updateReport' : IDL.Func(
      [ReportId, ReportUpdate],
      [IDL.Opt(DiagnosticReport)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DoctorId = IDL.Nat;
  const SlotInput = IDL.Record({
    'startTime' : IDL.Text,
    'doctorId' : DoctorId,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
  });
  const SlotId = IDL.Nat;
  const AvailabilitySlot = IDL.Record({
    'id' : SlotId,
    'startTime' : IDL.Text,
    'doctorId' : DoctorId,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const AppointmentId = IDL.Nat;
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : AppointmentStatus,
    'doctorId' : DoctorId,
    'bookedAt' : Timestamp,
    'patientId' : UserId,
    'slotId' : SlotId,
    'notes' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentInput = IDL.Record({
    'doctorId' : DoctorId,
    'slotId' : SlotId,
    'notes' : IDL.Opt(IDL.Text),
  });
  const DoctorInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'clinicAddress' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'clinicName' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'id' : DoctorId,
    'bio' : IDL.Opt(IDL.Text),
    'clinicAddress' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'clinicName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ReportType = IDL.Variant({
    'mri' : IDL.Null,
    'bloodTest' : IDL.Null,
    'other' : IDL.Text,
    'xRay' : IDL.Null,
    'ctScan' : IDL.Null,
    'ultrasound' : IDL.Null,
  });
  const ReportInput = IDL.Record({
    'title' : IDL.Text,
    'patientId' : UserId,
    'labNotes' : IDL.Opt(IDL.Text),
    'fileBlob' : IDL.Opt(ExternalBlob),
    'reportType' : ReportType,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  const ReportId = IDL.Nat;
  const ReportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'uploaded' : IDL.Null,
    'viewed' : IDL.Null,
  });
  const DiagnosticReport = IDL.Record({
    'id' : ReportId,
    'status' : ReportStatus,
    'title' : IDL.Text,
    'patientId' : UserId,
    'labNotes' : IDL.Opt(IDL.Text),
    'fileBlob' : IDL.Opt(ExternalBlob),
    'reportType' : ReportType,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'adminNotes' : IDL.Opt(IDL.Text),
    'uploadedAt' : Timestamp,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PatientProfile = IDL.Record({
    'id' : UserId,
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
    'phone' : IDL.Text,
  });
  const PatientProfileInput = IDL.Record({
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
    'phone' : IDL.Text,
  });
  const ReportUpdate = IDL.Record({
    'status' : IDL.Opt(ReportStatus),
    'title' : IDL.Opt(IDL.Text),
    'labNotes' : IDL.Opt(IDL.Text),
    'fileBlob' : IDL.Opt(ExternalBlob),
    'reportType' : IDL.Opt(ReportType),
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addDoctorSlot' : IDL.Func([SlotInput], [AvailabilitySlot], []),
    'adminCancelAppointment' : IDL.Func(
        [AppointmentId],
        [IDL.Opt(Appointment)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([AppointmentInput], [Appointment], []),
    'cancelMyAppointment' : IDL.Func(
        [AppointmentId],
        [IDL.Opt(Appointment)],
        [],
      ),
    'confirmAppointment' : IDL.Func(
        [AppointmentId],
        [IDL.Opt(Appointment)],
        [],
      ),
    'createDoctor' : IDL.Func([DoctorInput], [Doctor], []),
    'createReport' : IDL.Func([ReportInput], [DiagnosticReport], []),
    'deleteDoctor' : IDL.Func([DoctorId], [], []),
    'deletePatient' : IDL.Func([UserId], [], []),
    'deleteReport' : IDL.Func([ReportId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(Doctor)], ['query']),
    'getDoctorSlots' : IDL.Func(
        [DoctorId],
        [IDL.Vec(AvailabilitySlot)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
    'getPatientProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getReport' : IDL.Func([ReportId], [IDL.Opt(DiagnosticReport)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listAllPatients' : IDL.Func([], [IDL.Vec(PatientProfile)], ['query']),
    'listAllReports' : IDL.Func([], [IDL.Vec(DiagnosticReport)], ['query']),
    'listDoctors' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Doctor)], ['query']),
    'listMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listMyReports' : IDL.Func([], [IDL.Vec(DiagnosticReport)], ['query']),
    'markReportViewed' : IDL.Func([ReportId], [IDL.Opt(DiagnosticReport)], []),
    'removeDoctorSlot' : IDL.Func([SlotId], [], []),
    'saveMyProfile' : IDL.Func([PatientProfileInput], [PatientProfile], []),
    'setReportStatus' : IDL.Func(
        [ReportId, ReportStatus],
        [IDL.Opt(DiagnosticReport)],
        [],
      ),
    'updateDoctor' : IDL.Func([DoctorId, DoctorInput], [IDL.Opt(Doctor)], []),
    'updateReport' : IDL.Func(
        [ReportId, ReportUpdate],
        [IDL.Opt(DiagnosticReport)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };