/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'bookedAt' : Timestamp,
  'patientId' : UserId,
  'slotId' : SlotId,
  'notes' : [] | [string],
}
export type AppointmentId = bigint;
export interface AppointmentInput {
  'doctorId' : DoctorId,
  'slotId' : SlotId,
  'notes' : [] | [string],
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface AvailabilitySlot {
  'id' : SlotId,
  'startTime' : string,
  'doctorId' : DoctorId,
  'endTime' : string,
  'date' : string,
  'isBooked' : boolean,
}
export interface DiagnosticReport {
  'id' : ReportId,
  'status' : ReportStatus,
  'title' : string,
  'patientId' : UserId,
  'labNotes' : [] | [string],
  'fileBlob' : [] | [ExternalBlob],
  'reportType' : ReportType,
  'thumbnailBlob' : [] | [ExternalBlob],
  'adminNotes' : [] | [string],
  'uploadedAt' : Timestamp,
}
export interface Doctor {
  'id' : DoctorId,
  'bio' : [] | [string],
  'clinicAddress' : string,
  'name' : string,
  'email' : [] | [string],
  'specialization' : string,
  'phone' : string,
  'clinicName' : string,
}
export type DoctorId = bigint;
export interface DoctorInput {
  'bio' : [] | [string],
  'clinicAddress' : string,
  'name' : string,
  'email' : [] | [string],
  'specialization' : string,
  'phone' : string,
  'clinicName' : string,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface PatientProfile {
  'id' : UserId,
  'dateOfBirth' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'address' : [] | [string],
  'gender' : [] | [Gender],
  'phone' : string,
}
export interface PatientProfileInput {
  'dateOfBirth' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'gender' : [] | [Gender],
  'phone' : string,
}
export type ReportId = bigint;
export interface ReportInput {
  'title' : string,
  'patientId' : UserId,
  'labNotes' : [] | [string],
  'fileBlob' : [] | [ExternalBlob],
  'reportType' : ReportType,
  'thumbnailBlob' : [] | [ExternalBlob],
  'adminNotes' : [] | [string],
}
export type ReportStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'uploaded' : null } |
  { 'viewed' : null };
export type ReportType = { 'mri' : null } |
  { 'bloodTest' : null } |
  { 'other' : string } |
  { 'xRay' : null } |
  { 'ctScan' : null } |
  { 'ultrasound' : null };
export interface ReportUpdate {
  'status' : [] | [ReportStatus],
  'title' : [] | [string],
  'labNotes' : [] | [string],
  'fileBlob' : [] | [ExternalBlob],
  'reportType' : [] | [ReportType],
  'thumbnailBlob' : [] | [ExternalBlob],
  'adminNotes' : [] | [string],
}
export type SlotId = bigint;
export interface SlotInput {
  'startTime' : string,
  'doctorId' : DoctorId,
  'endTime' : string,
  'date' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addDoctorSlot' : ActorMethod<[SlotInput], AvailabilitySlot>,
  'adminCancelAppointment' : ActorMethod<[AppointmentId], [] | [Appointment]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[AppointmentInput], Appointment>,
  'cancelMyAppointment' : ActorMethod<[AppointmentId], [] | [Appointment]>,
  'confirmAppointment' : ActorMethod<[AppointmentId], [] | [Appointment]>,
  'createDoctor' : ActorMethod<[DoctorInput], Doctor>,
  'createReport' : ActorMethod<[ReportInput], DiagnosticReport>,
  'deleteDoctor' : ActorMethod<[DoctorId], undefined>,
  'deletePatient' : ActorMethod<[UserId], undefined>,
  'deleteReport' : ActorMethod<[ReportId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctor' : ActorMethod<[DoctorId], [] | [Doctor]>,
  'getDoctorSlots' : ActorMethod<[DoctorId], Array<AvailabilitySlot>>,
  'getMyProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getPatientProfile' : ActorMethod<[UserId], [] | [PatientProfile]>,
  'getReport' : ActorMethod<[ReportId], [] | [DiagnosticReport]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'listAllPatients' : ActorMethod<[], Array<PatientProfile>>,
  'listAllReports' : ActorMethod<[], Array<DiagnosticReport>>,
  'listDoctors' : ActorMethod<[[] | [string]], Array<Doctor>>,
  'listMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'listMyReports' : ActorMethod<[], Array<DiagnosticReport>>,
  'markReportViewed' : ActorMethod<[ReportId], [] | [DiagnosticReport]>,
  'removeDoctorSlot' : ActorMethod<[SlotId], undefined>,
  'saveMyProfile' : ActorMethod<[PatientProfileInput], PatientProfile>,
  'setReportStatus' : ActorMethod<
    [ReportId, ReportStatus],
    [] | [DiagnosticReport]
  >,
  'updateDoctor' : ActorMethod<[DoctorId, DoctorInput], [] | [Doctor]>,
  'updateReport' : ActorMethod<
    [ReportId, ReportUpdate],
    [] | [DiagnosticReport]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];