/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ReportInput {
    title: string;
    patientId: UserId;
    labNotes?: string;
    fileBlob?: ExternalBlob;
    reportType: ReportType;
    thumbnailBlob?: ExternalBlob;
    adminNotes?: string;
}
export type SlotId = bigint;
export type DoctorId = bigint;
export interface SlotInput {
    startTime: string;
    doctorId: DoctorId;
    endTime: string;
    date: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PatientProfileInput {
    dateOfBirth?: string;
    name: string;
    email?: string;
    address?: string;
    gender?: Gender;
    phone: string;
}
export interface DoctorInput {
    bio?: string;
    clinicAddress: string;
    name: string;
    email?: string;
    specialization: string;
    phone: string;
    clinicName: string;
}
export type ReportType = {
    __kind__: "mri";
    mri: null;
} | {
    __kind__: "bloodTest";
    bloodTest: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "xRay";
    xRay: null;
} | {
    __kind__: "ctScan";
    ctScan: null;
} | {
    __kind__: "ultrasound";
    ultrasound: null;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AvailabilitySlot {
    id: SlotId;
    startTime: string;
    doctorId: DoctorId;
    endTime: string;
    date: string;
    isBooked: boolean;
}
export type UserId = Principal;
export type ReportId = bigint;
export interface DiagnosticReport {
    id: ReportId;
    status: ReportStatus;
    title: string;
    patientId: UserId;
    labNotes?: string;
    fileBlob?: ExternalBlob;
    reportType: ReportType;
    thumbnailBlob?: ExternalBlob;
    adminNotes?: string;
    uploadedAt: Timestamp;
}
export type AppointmentId = bigint;
export interface ReportUpdate {
    status?: ReportStatus;
    title?: string;
    labNotes?: string;
    fileBlob?: ExternalBlob;
    reportType?: ReportType;
    thumbnailBlob?: ExternalBlob;
    adminNotes?: string;
}
export interface PatientProfile {
    id: UserId;
    dateOfBirth?: string;
    name: string;
    createdAt: Timestamp;
    email?: string;
    address?: string;
    gender?: Gender;
    phone: string;
}
export interface Doctor {
    id: DoctorId;
    bio?: string;
    clinicAddress: string;
    name: string;
    email?: string;
    specialization: string;
    phone: string;
    clinicName: string;
}
export interface Appointment {
    id: AppointmentId;
    status: AppointmentStatus;
    doctorId: DoctorId;
    bookedAt: Timestamp;
    patientId: UserId;
    slotId: SlotId;
    notes?: string;
}
export interface AppointmentInput {
    doctorId: DoctorId;
    slotId: SlotId;
    notes?: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum ReportStatus {
    pending = "pending",
    sent = "sent",
    uploaded = "uploaded",
    viewed = "viewed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addDoctorSlot(input: SlotInput): Promise<AvailabilitySlot>;
    adminCancelAppointment(id: AppointmentId): Promise<Appointment | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(input: AppointmentInput): Promise<Appointment>;
    cancelMyAppointment(id: AppointmentId): Promise<Appointment | null>;
    confirmAppointment(id: AppointmentId): Promise<Appointment | null>;
    createDoctor(input: DoctorInput): Promise<Doctor>;
    createReport(input: ReportInput): Promise<DiagnosticReport>;
    deleteDoctor(id: DoctorId): Promise<void>;
    deletePatient(patientId: UserId): Promise<void>;
    deleteReport(id: ReportId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getDoctor(id: DoctorId): Promise<Doctor | null>;
    getDoctorSlots(doctorId: DoctorId): Promise<Array<AvailabilitySlot>>;
    getMyProfile(): Promise<PatientProfile | null>;
    getPatientProfile(patientId: UserId): Promise<PatientProfile | null>;
    getReport(id: ReportId): Promise<DiagnosticReport | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllAppointments(): Promise<Array<Appointment>>;
    listAllPatients(): Promise<Array<PatientProfile>>;
    listAllReports(): Promise<Array<DiagnosticReport>>;
    listDoctors(specialization: string | null): Promise<Array<Doctor>>;
    listMyAppointments(): Promise<Array<Appointment>>;
    listMyReports(): Promise<Array<DiagnosticReport>>;
    markReportViewed(id: ReportId): Promise<DiagnosticReport | null>;
    removeDoctorSlot(slotId: SlotId): Promise<void>;
    saveMyProfile(input: PatientProfileInput): Promise<PatientProfile>;
    setReportStatus(id: ReportId, status: ReportStatus): Promise<DiagnosticReport | null>;
    updateDoctor(id: DoctorId, input: DoctorInput): Promise<Doctor | null>;
    updateReport(id: ReportId, update: ReportUpdate): Promise<DiagnosticReport | null>;
}
import type { Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentInput as _AppointmentInput, AppointmentStatus as _AppointmentStatus, DiagnosticReport as _DiagnosticReport, Doctor as _Doctor, DoctorId as _DoctorId, DoctorInput as _DoctorInput, ExternalBlob as _ExternalBlob, Gender as _Gender, PatientProfile as _PatientProfile, PatientProfileInput as _PatientProfileInput, ReportId as _ReportId, ReportInput as _ReportInput, ReportStatus as _ReportStatus, ReportType as _ReportType, ReportUpdate as _ReportUpdate, SlotId as _SlotId, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addDoctorSlot(arg0: SlotInput): Promise<AvailabilitySlot> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctorSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctorSlot(arg0);
            return result;
        }
    }
    async adminCancelAppointment(arg0: AppointmentId): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelAppointment(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelAppointment(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: AppointmentInput): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(to_candid_AppointmentInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Appointment_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(to_candid_AppointmentInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Appointment_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelMyAppointment(arg0: AppointmentId): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMyAppointment(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMyAppointment(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmAppointment(arg0: AppointmentId): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAppointment(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAppointment(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDoctor(arg0: DoctorInput): Promise<Doctor> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(to_candid_DoctorInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Doctor_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(to_candid_DoctorInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Doctor_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReport(arg0: ReportInput): Promise<DiagnosticReport> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(await to_candid_ReportInput_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DiagnosticReport_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(await to_candid_ReportInput_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DiagnosticReport_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDoctor(arg0: DoctorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deletePatient(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deleteReport(arg0: ReportId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctor(arg0: DoctorId): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorSlots(arg0: DoctorId): Promise<Array<AvailabilitySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorSlots(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientProfile(arg0: UserId): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: ReportId): Promise<DiagnosticReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAppointments();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAppointments();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllPatients(): Promise<Array<PatientProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPatients();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPatients();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllReports(): Promise<Array<DiagnosticReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllReports();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllReports();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDoctors(arg0: string | null): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDoctors(to_candid_opt_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDoctors(to_candid_opt_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAppointments();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAppointments();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyReports(): Promise<Array<DiagnosticReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyReports();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyReports();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async markReportViewed(arg0: ReportId): Promise<DiagnosticReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markReportViewed(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markReportViewed(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeDoctorSlot(arg0: SlotId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDoctorSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDoctorSlot(arg0);
            return result;
        }
    }
    async saveMyProfile(arg0: PatientProfileInput): Promise<PatientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyProfile(to_candid_PatientProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PatientProfile_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyProfile(to_candid_PatientProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PatientProfile_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async setReportStatus(arg0: ReportId, arg1: ReportStatus): Promise<DiagnosticReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setReportStatus(arg0, to_candid_ReportStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReportStatus(arg0, to_candid_ReportStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDoctor(arg0: DoctorId, arg1: DoctorInput): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, to_candid_DoctorInput_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, to_candid_DoctorInput_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReport(arg0: ReportId, arg1: ReportUpdate): Promise<DiagnosticReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(arg0, await to_candid_ReportUpdate_n56(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(arg0, await to_candid_ReportUpdate_n56(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_DiagnosticReport_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiagnosticReport): Promise<DiagnosticReport> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Doctor_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doctor): Doctor {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PatientProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientProfile): PatientProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ReportType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportType): ReportType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : from_candid_Doctor_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : from_candid_PatientProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Gender]): Gender | null {
    return value.length === 0 ? null : from_candid_Gender_n42(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiagnosticReport]): Promise<DiagnosticReport | null> {
    return value.length === 0 ? null : await from_candid_DiagnosticReport_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    status: _AppointmentStatus;
    doctorId: _DoctorId;
    bookedAt: _Timestamp;
    patientId: _UserId;
    slotId: _SlotId;
    notes: [] | [string];
}): {
    id: AppointmentId;
    status: AppointmentStatus;
    doctorId: DoctorId;
    bookedAt: Timestamp;
    patientId: UserId;
    slotId: SlotId;
    notes?: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n11(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        bookedAt: value.bookedAt,
        patientId: value.patientId,
        slotId: value.slotId,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DoctorId;
    bio: [] | [string];
    clinicAddress: string;
    name: string;
    email: [] | [string];
    specialization: string;
    phone: string;
    clinicName: string;
}): {
    id: DoctorId;
    bio?: string;
    clinicAddress: string;
    name: string;
    email?: string;
    specialization: string;
    phone: string;
    clinicName: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.bio)),
        clinicAddress: value.clinicAddress,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        specialization: value.specialization,
        phone: value.phone,
        clinicName: value.clinicName
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportId;
    status: _ReportStatus;
    title: string;
    patientId: _UserId;
    labNotes: [] | [string];
    fileBlob: [] | [_ExternalBlob];
    reportType: _ReportType;
    thumbnailBlob: [] | [_ExternalBlob];
    adminNotes: [] | [string];
    uploadedAt: _Timestamp;
}): Promise<{
    id: ReportId;
    status: ReportStatus;
    title: string;
    patientId: UserId;
    labNotes?: string;
    fileBlob?: ExternalBlob;
    reportType: ReportType;
    thumbnailBlob?: ExternalBlob;
    adminNotes?: string;
    uploadedAt: Timestamp;
}> {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n29(_uploadFile, _downloadFile, value.status),
        title: value.title,
        patientId: value.patientId,
        labNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.labNotes)),
        fileBlob: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.fileBlob)),
        reportType: from_candid_ReportType_n33(_uploadFile, _downloadFile, value.reportType),
        thumbnailBlob: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.thumbnailBlob)),
        adminNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.adminNotes)),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    dateOfBirth: [] | [string];
    name: string;
    createdAt: _Timestamp;
    email: [] | [string];
    address: [] | [string];
    gender: [] | [_Gender];
    phone: string;
}): {
    id: UserId;
    dateOfBirth?: string;
    name: string;
    createdAt: Timestamp;
    email?: string;
    address?: string;
    gender?: Gender;
    phone: string;
} {
    return {
        id: value.id,
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.dateOfBirth)),
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.address)),
        gender: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.gender)),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    uploaded: null;
} | {
    viewed: null;
}): ReportStatus {
    return "pending" in value ? ReportStatus.pending : "sent" in value ? ReportStatus.sent : "uploaded" in value ? ReportStatus.uploaded : "viewed" in value ? ReportStatus.viewed : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mri: null;
} | {
    bloodTest: null;
} | {
    other: string;
} | {
    xRay: null;
} | {
    ctScan: null;
} | {
    ultrasound: null;
}): {
    __kind__: "mri";
    mri: null;
} | {
    __kind__: "bloodTest";
    bloodTest: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "xRay";
    xRay: null;
} | {
    __kind__: "ctScan";
    ctScan: null;
} | {
    __kind__: "ultrasound";
    ultrasound: null;
} {
    return "mri" in value ? {
        __kind__: "mri",
        mri: value.mri
    } : "bloodTest" in value ? {
        __kind__: "bloodTest",
        bloodTest: value.bloodTest
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "xRay" in value ? {
        __kind__: "xRay",
        xRay: value.xRay
    } : "ctScan" in value ? {
        __kind__: "ctScan",
        ctScan: value.ctScan
    } : "ultrasound" in value ? {
        __kind__: "ultrasound",
        ultrasound: value.ultrasound
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientProfile>): Array<PatientProfile> {
    return value.map((x)=>from_candid_PatientProfile_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiagnosticReport>): Promise<Array<DiagnosticReport>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DiagnosticReport_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doctor>): Array<Doctor> {
    return value.map((x)=>from_candid_Doctor_n20(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentInput): _AppointmentInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_DoctorInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoctorInput): _DoctorInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_PatientProfileInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientProfileInput): _PatientProfileInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function to_candid_ReportInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportInput): Promise<_ReportInput> {
    return await to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_ReportType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): _ReportType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function to_candid_ReportUpdate_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportUpdate): Promise<_ReportUpdate> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doctorId: DoctorId;
    slotId: SlotId;
    notes?: string;
}): {
    doctorId: _DoctorId;
    slotId: _SlotId;
    notes: [] | [string];
} {
    return {
        doctorId: value.doctorId,
        slotId: value.slotId,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    clinicAddress: string;
    name: string;
    email?: string;
    specialization: string;
    phone: string;
    clinicName: string;
}): {
    bio: [] | [string];
    clinicAddress: string;
    name: string;
    email: [] | [string];
    specialization: string;
    phone: string;
    clinicName: string;
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        clinicAddress: value.clinicAddress,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        specialization: value.specialization,
        phone: value.phone,
        clinicName: value.clinicName
    };
}
async function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    patientId: UserId;
    labNotes?: string;
    fileBlob?: ExternalBlob;
    reportType: ReportType;
    thumbnailBlob?: ExternalBlob;
    adminNotes?: string;
}): Promise<{
    title: string;
    patientId: _UserId;
    labNotes: [] | [string];
    fileBlob: [] | [_ExternalBlob];
    reportType: _ReportType;
    thumbnailBlob: [] | [_ExternalBlob];
    adminNotes: [] | [string];
}> {
    return {
        title: value.title,
        patientId: value.patientId,
        labNotes: value.labNotes ? candid_some(value.labNotes) : candid_none(),
        fileBlob: value.fileBlob ? candid_some(await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.fileBlob)) : candid_none(),
        reportType: to_candid_ReportType_n25(_uploadFile, _downloadFile, value.reportType),
        thumbnailBlob: value.thumbnailBlob ? candid_some(await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.thumbnailBlob)) : candid_none(),
        adminNotes: value.adminNotes ? candid_some(value.adminNotes) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth?: string;
    name: string;
    email?: string;
    address?: string;
    gender?: Gender;
    phone: string;
}): {
    dateOfBirth: [] | [string];
    name: string;
    email: [] | [string];
    address: [] | [string];
    gender: [] | [_Gender];
    phone: string;
} {
    return {
        dateOfBirth: value.dateOfBirth ? candid_some(value.dateOfBirth) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        gender: value.gender ? candid_some(to_candid_Gender_n52(_uploadFile, _downloadFile, value.gender)) : candid_none(),
        phone: value.phone
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ReportStatus;
    title?: string;
    labNotes?: string;
    fileBlob?: ExternalBlob;
    reportType?: ReportType;
    thumbnailBlob?: ExternalBlob;
    adminNotes?: string;
}): Promise<{
    status: [] | [_ReportStatus];
    title: [] | [string];
    labNotes: [] | [string];
    fileBlob: [] | [_ExternalBlob];
    reportType: [] | [_ReportType];
    thumbnailBlob: [] | [_ExternalBlob];
    adminNotes: [] | [string];
}> {
    return {
        status: value.status ? candid_some(to_candid_ReportStatus_n54(_uploadFile, _downloadFile, value.status)) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        labNotes: value.labNotes ? candid_some(value.labNotes) : candid_none(),
        fileBlob: value.fileBlob ? candid_some(await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.fileBlob)) : candid_none(),
        reportType: value.reportType ? candid_some(to_candid_ReportType_n25(_uploadFile, _downloadFile, value.reportType)) : candid_none(),
        thumbnailBlob: value.thumbnailBlob ? candid_some(await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.thumbnailBlob)) : candid_none(),
        adminNotes: value.adminNotes ? candid_some(value.adminNotes) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "mri";
    mri: null;
} | {
    __kind__: "bloodTest";
    bloodTest: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "xRay";
    xRay: null;
} | {
    __kind__: "ctScan";
    ctScan: null;
} | {
    __kind__: "ultrasound";
    ultrasound: null;
}): {
    mri: null;
} | {
    bloodTest: null;
} | {
    other: string;
} | {
    xRay: null;
} | {
    ctScan: null;
} | {
    ultrasound: null;
} {
    return value.__kind__ === "mri" ? {
        mri: value.mri
    } : value.__kind__ === "bloodTest" ? {
        bloodTest: value.bloodTest
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "xRay" ? {
        xRay: value.xRay
    } : value.__kind__ === "ctScan" ? {
        ctScan: value.ctScan
    } : value.__kind__ === "ultrasound" ? {
        ultrasound: value.ultrasound
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    pending: null;
} | {
    sent: null;
} | {
    uploaded: null;
} | {
    viewed: null;
} {
    return value == ReportStatus.pending ? {
        pending: null
    } : value == ReportStatus.sent ? {
        sent: null
    } : value == ReportStatus.uploaded ? {
        uploaded: null
    } : value == ReportStatus.viewed ? {
        viewed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
